#!/bin/bash

if [ "${1}" = "debug" -o "${1}" = "-x" ]; then
    set -x
    debug=true
    shift
fi
# we define this here and use it later; it might be ''
# we do it now to set -u, defensively, just in case
option="${1}"

# get defensive
set -u

# load handy functions, especially die
[ -f ~/.bashMyFuncs ] && source ~/.bashMyFuncs || { echo Cannot proceed; exit 1; }

# who are we?
ourExec=$(basename $0)
# what are we doing?
ourConf=~/.${ourExec}.conf
[ -f "${ourConf}" ] && { source "${ourConf}" || die "Cannot source ${ourConf}, exiting." ; } || die "No '${ourConf}', exiting."
# now we should be able to tell what we are really doing!
[ -f "${realConf}" ] && { source "${realConf}" || die "Cannot source ${realConf}, exiting." ; } || die "No '${realConf}', exiting."
# test that to be sure

[[ -z $theWar ]] && die "Variable 'theWar' not set. Check '${realConf}'."
[[ ! -d ${sourceDir} || ! -d ${targetDir} ]] && { echo; echo "WARNING! Missing source and target folders!"; }

function camstart {
    { dockerStatus > /dev/null || { echo Starting docker too; ~/bin/myDocker start; } ; } || { echo could not start docker; exit 3; }
    # pww 2020-03-05 add a long delay, now that we have a much heavier docker
    ~/camunda/start-camunda.sh ${ourDelay:-15}
}
function camstop {
    ~/camunda/shutdown-camunda.sh
}
function latestwar {
    ls -lit ${sourceDir}/*war |head -1
}
function lsTheWar {
    ls -lit ${sourceDir}/${theWar} ${targetDir}/${theWar}
}
function lswars {
    ls -lit ${sourceDir}/*war ${targetDir}/*war
}
function warcopy {
    sourceWar="${sourceDir}/${theWar}"
    targetWar="${targetDir}/${theWar}"
    cp -p ${sourceWar} ${targetWar} || die "Could not copy '${sourceWar}' to '${targetWar}'"
    # this is a safety measure - unset, use, reset
    set +u
    cockpitModFiles="${cockpitModFiles}"
    set -u
    if [[ ! -z $cockpitModFiles ]]; then
        for file in $cockpitModFiles ; do
            cp ${jsSrcDir}/${file} ${jsTgtDir} || echo error copying $file
        done
    else
        # if cockpitModFiles is empty, make sure we clean up any config.js
        # left over from a previous war, e.g., going from tra->sample
        rm -f ${jsTgtDir}/config.js
        # what else is in the folder?
        echo "Contents of '${jsTgtDir}': $(ls ${jsTgtDir})"
        # we could automate this by parsing the config.js, but we won't, yet
    fi
}

function listConfigs {
    echo Available configurations:
    echo
    ls -lt ${ourConf}.*
    echo
    echo Current configuration is ${realConf}:
    echo
    cat ${realConf}
}

function camundaStatus {
    rc=$(true)
    pgrep -fi tomcat > /dev/null && echo Camunda should be active || { echo "No active Camunda, tomcat is not running."; rc=$(false); }
    return $rc
}

function dockerStatus {
    rc=$(true)
    ss -t -l -n | grep -q 389  && echo LDAP active on this host || { echo "No LDAP on this host, is docker running?"; rc=$(false); }
    return $rc
}

function status {
    rc=$(true)
    camundaStatus || rc=$(false)
    dockerStatus  || rc=$(false)
    return $rc
}

function chooseAnOption {
    cat << EOM

    Do you wish to
        1) Start Camunda
        2) Stop Camunda
        3) Restart Camunda with a new war file
        4) Restart Camunda with the current war file
        5) Check the date of all war files
        6) List available config files
        7) Check process status
        q) Quit
    ??? (Note that other options are available from the command line.)
EOM
    echo -n "Please enter your choice: "
    read answer
    echo
    case $answer in
        1)
            option="start"
            ;;
        2)
            option="stop"
            ;;
        3)
            option="newwar"
            ;;
        4)
            option="restart"
            ;;
        5)
            option="lswars"
            ;;
        6)  option="listConfigs"
            ;;
        7)
            option="status"
            ;;
        q|Q)
            option="quit"
            ;;
        *)
            option="usage"
            ;;
    esac
}

# option was defined above - we use it now
[ -z "${option}" ] && chooseAnOption
ourDelay="${2:-15}"

shopt -s nocasematch
case $option in
    start)
        camstart
        ;;
    stop)
        camstop
        ;;
    stopall|hardstop)
        camstop
        ~/bin/myDocker stop
        ;;
    kick|restart)
        camstop
        camstart
        ;;
    hard|hardkick)
        camstop
        ~/bin/myDocker stop
        camstart
        ;;
    checkwar|checkthewar|lsthewar)
        lsTheWar
        ;;
    newwar)
        camstop
        warcopy
        camstart
        ;;
    lswar|curwar|lswars|curwars)
        lswars
        ;;
    latestwar)
        latestwar
        ;;
    warcopy)
        warcopy
        ;;
    debug|-x)
        echo "You should have specified those first; bit too late now."
        ;;
    listConfigs)
        listConfigs
        ;;
    status)
        status
        ;;
    quit)
        echo "Goodbye."
        exit 0
        ;;
    *)
        echo "$0 [ debug | -x ] start | stop | status | (kick | restart) | newwar | warcopy | (lswar | curwar) | latestwar | lsthewar"
        ;;
esac
echo
