#!/bin/sh

lead="${1}"

ls * > /dev/null 2>&1 || exit

curdir=$(pwd)
echo "${lead}${curdir}/"

lead="${lead}    "
dirs=""
for file in *; do
#ls | while read file; do
    if [ -d "${file}" ]; then
        dirs="${dirs} ${file}"
    else
        echo "${lead}$(ls -F ${file})"
    fi
done

for dir in $dirs; do
#ls -d $dirs | while read dir; do
    cd "${dir}" 2> /dev/null
    $0 "${lead}"
    cd .. 2> /dev/null
done
