#!/bin/bash

cd ~/docker
case $1 in
    start|run)
        ./run.sh
        ;;
    stop)
        ./stop.sh
        ;;
    restart)
        ./stop.sh
        ./run.sh
        ;;
    *)
        ls
        ;;
esac
exit 0
