#!/usr/bin/env bash

[[ $1 == "-x" ]] && { set -x; shift; }
resetFlag=""
[[ $1 == "reset" ]] && { resetFlag=$1; shift; }

# just set it, empty or full, works either way
justThisType=$1
thisTypeDone=$2

set -u

patterns=allTypeDefinitions
typesDone=typesComplete

curDir=$(pwd)
case $curDir in
    *black*red*|*red*black*)
        echo $curDir makes no sense
        ;;
    *black*)
        COLOUR=black
        ;;
    *red*)
        COLOUR=red
        ;;
    *)
        echo $curDir is neither black nor red, exiting
        exit 1
        ;;
esac

teFilePattern='z*te'
allTEfiles=$(echo z*te)
# doublequote the pattern to preserve it from globbing in the comparison
[[ $allTEfiles == "$teFilePattern" ]] && { echo No TE files in $curDir, exiting.; exit 1; }

[[ ! -s $patterns ]] && resetFlag="reset"
# we have to use this instead of touch because of some grep -v -f oddities....
[[ ! -s $typesDone ]] && echo '#' > $typesDone

resetPatterns () {
    # old way
    # grep "type *${COLOUR}.*_t" z-${COLOUR}-*te | cut -d: -f2 | sed -e 's/type//' -e 's/;//' -e 's/[[:space:]]//g' | sort -u | grep -v -f $typesDone > $patterns

    {
    awk '
        # set our block marker, not in a block yet
        BEGIN {
            inBlock=0
        }

        # skip lines that begin with comments
        /^[[:space:]]*#/ {
            next
        }
        # determine if we are in a block; skip to the next line if so
        /{[^}]*/ {
            inBlock=1
            next
        }
        # determine if we are exiting a block; skip to the next line if so
        /[^{]*}/ {
            inBlock=0
            next
        }
        # look for likely lines
        # likely attribute definitions
        /^[[:space:]]*attribute[[:space:]]+/ {
            # if we are not in a block, any line beginning with <whitespace>attribute
            # should be an attribute definition
            if (inBlock == 0 ) {
                gsub(/;/, "", $2)
                print $2
            }
            # if we are in a block, do nothing
        }
        # likely type definitions
        /^[[:space:]]*type[[:space:]]+/ {
            # if we are not in a block, any line beginning with <whitespace>type
            # should be a type definition
            if (inBlock == 0 ) {
                gsub(/[,;]/, "", $2)
                print $2
            }
            # if we are in a block, do nothing
        }
        # nothing to do here, right?
        END {
        }
    ' z-${COLOUR}-*te
    #' z-${COLOUR}-*te | sort -u | grep -v -f $typesDone > $patterns
    cut -d: -f3 z-${COLOUR}-*fc
    }| sort -u | grep -v -f $typesDone > $patterns

}
[[ $resetFlag == "reset" ]] && resetPatterns

findThisPattern () {
    pattern=$1
    definedIn=$(grep -l -e "^attribute[[:space:]]*${pattern}[,; ]" -e "^type[[:space:]]*${pattern}[,; ]" $allTEfiles)
    if [[ -z $definedIn ]]; then
        echo "There is no definition for $pattern"
        otherTEfiles=$allTEfiles
    else
        echo -e "$pattern defined in:\t $definedIn"
        otherTEfiles=$(echo $allTEfiles | sed -e "s,${definedIn},,")
    fi
    if grep -q $pattern $otherTEfiles; then
        cat << EOM
$pattern is used in
$(grep -l $pattern $otherTEfiles)
EOM
    fi
    if grep -q $pattern *fc; then
        cat << EOM
$pattern is used in
$(grep -l $pattern *fc)
EOM
    fi
    echo
}

if [[ -z $justThisType ]]; then
    for pattern in $(grep -v '^#' ${patterns}); do
        findThisPattern $pattern
    done
else
    findThisPattern $justThisType
    if [[ $thisTypeDone == "done" ]]; then
        echo $justThisType >> $typesDone
        $0 reset
    fi
fi
