#!/usr/bin/env bash
[[ $1 == "-d" ]] && debug () { return 0; } || debug () { return 1; }

myHost=$(hostname)
myKeyDB=~/myKeyDB
myKeyDB=$(echo $myKeyDB)

declare -A myKeys
declare -A myHosts
declare -A keysToHosts

workingDir=~/.ssh/
workingDir=$(echo $workingDir)

cfgFile="${workingDir}/config"

[[ ! -d $workingDir ]] && {
    echo "Cannot locate .ssh folder '${workingDir}', exiting"
    exit 1
}

cd $workingDir || {
    echo "Cannot cd to .ssh folder '${workingDir}', exiting"
    exit 3
}

# first, get basic data about all of our keys
for pubKey in *pub; do
    privKey=$(basename $pubKey .pub)
    fullDetails=$(ssh-keygen -l -f $pubKey)
    read bitLength fullFingerPrint myId algorithm <<<${fullDetails}
    algorithm=$(echo $algorithm | tr -d '()')
    IFS=: read hashType fingerPrint <<<${fullFingerPrint}
    debug && echo $fingerPrint $hashType $myId $algorithm $bitLength $privKey
    myKeys[${fingerPrint}]="$hashType:$privKey:$myId:$algorithm:$bitLength"
done

echo

debug && for key in "${!myKeys[@]}"; do
    echo ${myKeys[$key]}
done

# check out each config entry
[[ ! -f $cfgFile ]] && {
    echo There is no cfgFile on this host
}

comment='^[[:space:]]#'
hostLine='^Host[[:space:]]'
idenLine='^IdentityFile'
nameLine='^Hostname'
userLine='^User'
blankLine='^[[:space:]]*$'
curHost=''
curIden=''
curName=''
curUser=''
while read -r LINE; do
    [[ $LINE =~ $hostLine ]] && {
        [[ ! -z $curHost ]] && {
            debug && echo "'$myHost:$curHost:$curIden:$curName:$curUser'"
            myHosts[${myHost}:${curHost}]="$curIden:$curName:$curUser"
        }
        curHost=${LINE##*[[:space:]]}
    }
    [[ $LINE =~ $idenLine ]] && {
        curIden=$(basename ${LINE##*[[:space:]]})
    }
    [[ $LINE =~ $userLine ]] && {
        curUser=${LINE##*[[:space:]]}
    }
    [[ $LINE =~ $nameLine ]] && {
        curName=${LINE##*[[:space:]]}
    }
    [[ $LINE =~ $blankLine || $LINE =~ $comment ]] && continue
done < $cfgFile
# get the last one
debug && echo "'$myHost:$curHost:$curIden:$curName:$curUser'"
myHosts[${myHost}:${curHost}]="$curIden:$curName:$curUser"

for key in "${!myHosts[@]}"; do
    hostFrom=${key%:*}
    hostTo=${key#*:}
    echo $hostFrom goes to $hostTo using ${myHosts[$key]}
    #continue
    thisKey=${myHosts[$key]%%:*}
    fullDetails=$(ssh-keygen -l -f $thisKey)
    read bitLength fullFingerPrint myId algorithm <<<${fullDetails}
    algorithm=$(echo $algorithm | tr -d '()')
    IFS=: read hashType fingerPrint <<<${fullFingerPrint}
    echo -e "\t\t\tFingerprint: $fingerPrint"
    echo
    keysToHosts[$thisKey]+="$hostTo "
done

for key in "${!myKeys[@]}"; do
    IFS=: read hashType keyFile theRest <<<${myKeys[$key]}
    keyDate=$(ls -l --time-style='+%Y-%m-%d' $keyFile 2> /dev/null|tr -s ' '| cut -d' ' -f6)
    [[ -z $keyDate ]] && keyDate=$(ls -l  $keyFile 2> /dev/null|tr -s ' '| cut -d' ' -f6-8)
    [[ -z $keyDate ]] && keyGenMsg="$keyFile" || keyGenMsg="${keyFile}, generated $keyDate,"
    if [[ -z ${keysToHosts[$keyFile]} ]]; then
        echo $keyGenMsg is NOT used
    else
        echo $keyGenMsg is used for
        for host in ${keysToHosts[$keyFile]}; do
            echo -e "\t\t$host"
        done
    fi
    echo
done
