#!/usr/bin/env bash

# everything should be good to go now; get defensive
set -u

VIMPLUGS="vimplugs"
VIMPACKS="vimpacks"
MANIFEST="manifest"
DOVIM=""
NODOVIM=""
declare -A DO_DIRS
DO_DIRS[myBinFiles]=~/bin
DO_DIRS[myDotFiles]=~
declare -a DO_THESE=()

init=""
while getopts iV opt; do case $opt in
    i) init="yes";;
    V) NODOVIM="yesWhichMeansNo" ;;
    *) printf >&2 "Unknown option '%s', ignoring\n" "${opt}" ;;
esac; done
shift $((OPTIND - 1))
[[ $# -eq 1 && -d "$1" ]] && cd "$1"

# are we doing a specific directory, or all?
# first, check our cwd to determine if specific
myDir=$(pwd)
baseDir=$(basename "${myDir}")
for dir in "${!DO_DIRS[@]}"; do
    [[ $baseDir == "$dir" ]] && { DO_THESE+=("$myDir"); break; }
done

if [[ ${#DO_THESE[@]} -eq 0 ]]; then
    # we are doing all of them....
    # first, make sure we can find one and only one of each one
    for dir in "${!DO_DIRS[@]}"; do
        possibleDir=$(find ~ -xdev -type d -name "${dir}" -print 2> /dev/null)
        dirCount=$(echo "${possibleDir}" | wc -l)
        if [[ $dirCount -ne 1 ]]; then
            printf >&2 "For '%s', wanted one dir, got %s, skipping\n" "${dir}" "${dirCount}"
            continue
        fi
        DO_THESE+=("$possibleDir")
    done
fi

# DO_THESE is set to one or more directories to be processed;
# carry on....

diffColorOption () {
    if diff --color=always . . 2> /dev/null; then
        echo "--color=always"
    else
        echo ""
    fi
}

replaceOrSwap () {
    anyDiffs=yes
    diff $(diffColorOption) -u ${compareWith}/${file} ${dir}/${file}
    echo; echo "If + is wanted, 'y'; if - is wanted, 'swap'; 'd' deletes '-'; otherwise, anything else."
    read -p "Replace $file in ~? " answer
    case $answer in
        y*|Y*)
            makeOrUpdate
            ;;
        swap)
            replace
            ;;
        d)
            rm ${compareWith}/${file}
            ;;
        *)
            :
            ;;
    esac
}

replace () {
    cp -p ${compareWith}/${file} ${dir}/${file} || printf >&2 "Error copying!!!\n"
}

makeOrUpdate () {
    cp -p ${dir}/${file} ${compareWith}/${file} || printf >&2 "Error copying!!!\n"
}

addMissing () {
    doIt="no"
    anyDiffs=yes
    if [[ $init == "yes" ]]; then
        doIt="yes"
    else
        echo "The file '${compareWith}/${file}' does not exist;"
        read -p "createit from '${dir}/${file}'? " answer
        case $answer in
            y*|Y*)
                doIt="yes"
                ;;
            *)
                :
                ;;
        esac
    fi
    [[ $doIt == "yes" ]] && makeOrUpdate
}

for dir in "${DO_THESE[@]}"; do
    baseDir=$(basename "${dir}")
    compareWith=${DO_DIRS[$baseDir]}
    case $baseDir in
        myBinFiles)
            if [[ ! -f $compareWith ]]; then
                mkdir -p $compareWith
            fi
            DOVIM=""
            ;;
        myDotFiles)
            [[ ! $NODOVIM ]] && DOVIM="yes"
            ;;
    esac
    theManifest="${dir}/${MANIFEST}"
    [[ ! -f ${theManifest} || ! -s ${theManifest} ]] && { printf >&2 "No manifest, very odd, skipping '%s'.\n" "${dir}"; continue; }

    (
        # this sets fileManifest
        source "${theManifest}" || { printf >&2 "Cannot source '%s', exiting.\n" "${theManifest}"; exit 7; }

        anyDiffs=no
        for file in $fileManifest; do
            [[ ! -f ${compareWith}/${file} ]] && { addMissing; continue; }
            diff -q ${compareWith}/${file} ${dir}/${file} 2> /dev/null || { replaceOrSwap; continue; }
        done

        [[ ${anyDiffs} = no ]] && { printf >&2 "No diffs, no need to change anything.\n"; git -C $dir status; } || true
    )

    if [[ $DOVIM ]]; then
        if type ${VIMPLUGS} &> /dev/null; then
            ${VIMPLUGS} ${dir}/${VIMPACKS}
        else
            printf >&2 "Update bin files first, please\n"
            exit 1
        fi
    fi

done
