#!/bin/bash

myItems () {
    rc=$(true)
    curdir="$(pwd)"
    for folder in ~/myDotFiles ~/myBinFiles; do
        echo "Doing '$folder'"
        cd $folder
        git pull
        ./status
        read -p "Continue? " answer
        case $answer in
            y*|Y*)
                continue
                ;;
            *)
                rc=$(false)
                break
                ;;
        esac
    done
    cd "$curdir"
    return $rc
}

brewItems () {
    type brew &> /dev/null || return
    runBrewCleanup () {
        read -p "Run 'brew cleanup'? " answer
        case $answer in
            y*|Y*)
                brew cleanup
                ;;
            *)
                :
                ;;
        esac
    }
    echo Updating brew....
    brew update
    echo Upgrading brew....
    brew upgrade
    echo Checking brew....
    brew doctor || runBrewCleanup
    echo
}

gemItems () {
    type gem &> /dev/null || return
    read -p "Ready to continue with gems (ctrl-c to skip)? " answer
    echo Updating gems
    gem update
    echo $gemProbs
}

nodeItems () {
    type npm &> /dev/null || return
    read -p "Ready to continue with npm and node (ctrl-c to skip)? " answer
    npm-check -u -g
    npm-check -u
    node -v
    npm -v
}

myItems || exit $(false)
brewItems
gemItems
nodeItems

