#!/bin/bash

brewItems () {
    type brew &> /dev/null || return
    runBrewCleanup () {
        read -p "Run 'brew cleanup'? " answer
        case $answer in
            y*|Y*)
                brew cleanup
                ;;
            *)
                :
                ;;
        esac
    }
    echo Updating brew....
    brew update
    echo Upgrading brew....
    brew upgrade
    echo Checking brew....
    brew doctor || runBrewCleanup
    echo
}

gemItems () {
    type gem &> /dev/null || return
    read -p "Ready to continue with gems (ctrl-c to skip)? " answer
    echo Updating gems
    gem update
    echo $gemProbs
}

nodeItems () {
    type npm &> /dev/null || return
    read -p "Ready to continue with npm and node (ctrl-c to skip)? " answer
    npm-check -u -g
    npm-check -u
    node -v
    npm -v
}

brewItems
gemItems
nodeItems

